# Generated by Django 5.0.2 on 2024-02-29 22:20

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Email",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("content", models.TextField()),
                (
                    "classification",
                    models.CharField(
                        blank=True,
                        choices=[("regular", "Regular"), ("newsletter", "Newsletter")],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("is_classified", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
